### PR TITLE
Add Easy Coding Standard

### PR DESCRIPTION
**Pull request by driftingly**
This PR adds Easy Coding Standard as an additional option.
This does not change any existing functionality. 

## Why?

Over on [TLint](https://github.com/tighten/tlint), we end up writing custom Linters and Formatters that are already covered by [PHP CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) or [PHP Coding Standards Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer).  The goal of TLint is to pick up where PHP Codesniffer leaves off.  To save development time (especially when it comes to writing formatters) I would like to include PHP Coding Standards Fixer in this base. 

Easy Coding Standard accomplishes this by combining these two tools into one configuration.  TLint will be able to focus on Linters and Formatters which **cannot** be covered by these tools.  Any additional sniffs and fixers which can be added to these tools should be.

## Transitioning to Easy Coding Standard

- [x] Add ECS option to Tighten Coding Standards repo starting with PSR-12 and Tighten preferences 
- [x] Move any TLint linters or formatters over (check issues as well)
- [x] Create custom sniffs where we are able
- [x] Add Laravel preset - look at TLint for different options.
- [x] Update [Duster](https://github.com/tighten/duster) to include ECS option

**Standards**
- [PHP-FIG PSR 1](https://www.php-fig.org/psr/psr-1/)
- [PHP-FIG PSR-12](https://www.php-fig.org/psr/psr-12/)
- [EasyCodingStandard PSR-1](https://github.com/symplify/symplify/blob/main/packages/easy-coding-standard/config/set/psr1.php) 
- [EasyCodingStandard PSR-12](https://github.com/symplify/symplify/blob/main/packages/easy-coding-standard/config/set/psr12.php)
    - Includes [PHP CS Fixer PSR-2](https://github.com/symplify/symplify/blob/main/packages/easy-coding-standard/config/set/php_cs_fixer/php-cs-fixer-psr2.php)

**Syntax Highlighting**

A lot of people rely on TLint syntax highlighting, there's a VS Code plug-in, I don't think there will be anything official given the [opinions of the creator Tomas Votruba](https://tomasvotruba.com/blog/2019/06/24/do-you-use-php-codesniffer-and-php-cs-fixer-phpstorm-plugin-you-are-slow-and-expensive/).  There is an ECS [plugin for VS Code](https://marketplace.visualstudio.com/items?itemName=azdanov.vscode-easy-coding-standard).

## Current TLint Linters Covered By ECS

- [x] `AlphabeticalImports` - OrderedImportsFixer
- [x] `ClassThingsOrder` - CustomOrderedClassElementsFixer (custom)
- [x] `ConcatenationNoSpacing` - ConcatSpaceFixer
- [x] `ConcatenationSpacing` - PSR-12 set
- [x] `NewLineAtEndOfFile` - PSR-2 set
- [x] `NoCompact` - ForbiddenFunctionsSniff
- [x] `NoDump` - ForbiddenFunctionsSniff
- [x] `NoInlineVarDocs` - NoInlineVarDocFixer (custom)
- [x] `NoStringInterpolationWithoutBraces` - ExplicitStringVariableFixer & SimpleToComplexStringVariableFixer
- [x] `NoUnusedImports` - NoUnusedImportsFixer
- [x] `SpaceAfterSoleNotOperator` - NotOperatorWithSuccessorSpaceFixer
- [x] `TrailingCommasOnArrays` - TrailingCommaInMultilineFixer [Rule][TrailingCommaInMultilineFixerRule] [Class][TrailingCommaInMultilineFixerClass]
- [x] `UseConfigOverEnv` - ForbiddenFunctionsSniff

### CODE REVIEW

**Comment by driftingly** [comment]
Look into `return new class() extends Migration {` <- this curly brace gets pulled up.

**Comment by mattstauffer** [comment]
@driftingly I'd like to have both this repo and Duster, preferably, have a single preferred way of going about vs. options.

Is this something that takes Duster and this repo from one option to two options? Or is just extending the tooling you get here?

And what do we get from ECS that we didn't get CodeSniffer?

And, if this _is_ introducing two different options, and if we _are_ getting more from ECS than we did from CodeSniffer, especially if that's true in a way that allows us to shrink down TLint... Is there any reason to even keep the PHP CodeSniffer config in here?

**Comment by driftingly** [comment]
@mattstauffer As it is now, this does add an option to the `tighten-coding-standard`.  I didn't want to come in and make too many presumptuous changes, and there is one feature missing from ECS, IDE support.

It may be helpful to share my thinking on the topic.  The primary purpose of any coding standard is to ensure the codebase adheres to a set of predetermined rules defining preferences on style and functionality.  The two main packages PHP developers use are CodeSniffer and PHP CS Fixer.  These two packages differ slightly in philosophy; CodeSniffer's original goal was to find potential violations, and PHP CS Fixer's goal was only to fix violations.  These differences mean you cannot solely rely on one to handle all standards.  In the ECS config `tighten.php`, we are relying on both tools. 

**And what do we get from ECS that we didn't get CodeSniffer?**

We have access to sniffs and fixes from both tools.  ECS allows us to remove several redundant linters and formatters from TLint.

**Is there any reason to even keep the PHP CodeSniffer config in here?**

The only reason to keep PHP CodeSniffer is to keep IDE inline feedback.  That being said, if the goal of Duster is to 'automatically apply Tighten's default code style for Laravel apps', then having IDE feedback is a distraction, it encourages the developer to fix violations manually, taking time and attention away from the problem they are trying to solve.  By removing PHP CodeSniffer we remove the IDE support some users may expect so it would definitely require a major version bump. 

**Duster**

Duster can be updated it use ECS under the hood and alias out the existing commands to maintain backwards compatibility while adding new ones.

In looking into this I just ran across this issue where ECS is discussed: https://github.com/tighten/duster/issues/22

**Comment by driftingly** [comment]
Closing this to use Laravel Pint.

**Pull request closed without merging**
